name: maarta
favicon: null
layout_spectrum: 0.05999
typography_spectrum: 0.63612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#505050'
    - '#838383'
    - '#272727'
    - '#b4b4b4'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
