favicon: null
name: maarta
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  lightness: 0
  brandStrength: 1
  brandColors:
    - '#f4e6c9'
    - '#cec3a7'
    - '#807562'
    - '#170b00'
    - '#bd8753'
  rhythmicContrast: 0
typography_spectrum: 0.2617021
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
