typography_spectrum: 0.7799326
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 1
title: meditation & art alliance
purpose: []
color:
  saturation: 0
  brandStrength: 0.5293843
  rhythmicContrast: 0.5
  brandColors:
    - '#FFFFFF'
    - '#393939'
    - '#7E7E7E'
    - '#999999'
    - '#DDDDDD'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: maarta
