name: maarta
favicon: null
layout_spectrum: 0.51157
typography_spectrum: 0.63612
title: 'meditation & art alliance'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4e6c9'
    - '#cec3a7'
    - '#807562'
    - '#170b00'
    - '#bd8753'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
