typography_spectrum: 0.7799326
color:
  saturation: 0
  brandStrength: 0.5293843
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#393939'
    - '#7E7E7E'
    - '#999999'
    - '#DDDDDD'
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: maarta
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About
    url: 'http://maarta.com'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: meditation & art alliance
purpose: []
